development:
  adapter: postgresql
  encoding: unicode
  database: lab_development
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lab_test
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: lab_production
  username: postgres
  password:
